### ISSUE TITLE
Add "Grafana Pandas Datasource"

### ISSUE THREAD

**Issue by amotl** [zuchka/grafana-awesome#3]
Dear Matt,

thanks a stack for creating this curated list of resources.

After you added `grafana-wtf` and @marcusolsson added `grafanimate` (#2), you might also be interested in adding `grafana-pandas-datasource` [1], in order to support all Python people out there. It has been created from code originally conceived by @linar-jether at [2] and converged into a real repository the other day [3].

Two specific examples that demonstrate its functionality, with screenshots, can be found at [4,5].

As with everything FOSS, it could definitively need some regular love. Please let me know if you observe any issues with it.

With kind regards,
Andreas.

[1] https://github.com/panodata/grafana-pandas-datasource
[2] https://gist.github.com/linar-jether/95ff412f9d19fdf5e51293eb0c09b850
[3] https://github.com/panodata/grafana-pandas-datasource/issues/1
[4] https://github.com/panodata/grafana-pandas-datasource/tree/main/examples/sinewave-midnights
[5] https://github.com/panodata/grafana-pandas-datasource/tree/main/examples/phenodata-mellifera

**Comment by zuchka** [comment]
@amotl this is a fantastic idea and an even better tool!

I should ping our internal Python and ML / Data Science channels about this 💯 

will add this today--thanks for the suggestion, and for all your Grafana love!

**Comment by amotl** [comment]
Thanks Matt. Kudos definitively go to @linar-jether, who conceived this excellent piece of code the other day [2].
